config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations"}
  root to: "users#index"

  get "/auth/:provider/callback", to: "omni_sessions#create"

  resources :promos

  resources :products
  resources :users do
    collection do
      get 'login', action: :login #users/login
      post 'login', action: :do_login
      delete 'login', action: :logout
      get 'search' # users/search
    end
  end

  
  get 'sells/index'

  get 'sells/:id', to: 'sells#show'

end

app/models/promo.rb
class Promo < ActiveRecord::Base
	validates_presence_of :title, :product, :discount
	validates_numericality_of :discount, 
		{ greater_than: 0, less_than: 100 }

	belongs_to :product

end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:title, :content, :product, :start_date, :finish_date, :discount)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_for(@promo) do |f| %>
  <% if @promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% @promo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :finish_date %><br>
    <%= f.date_select :finish_date %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.number_field :discount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing Promo</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Promos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Product</th>
      <th>Start date</th>
      <th>Finish date</th>
      <th>Discount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promos.each do |promo| %>
      <tr>
        <td><%= promo.title %></td>
        <td><%= promo.content %></td>
        <td><%= promo.product %></td>
        <td><%= promo.start_date %></td>
        <td><%= promo.finish_date %></td>
        <td><%= promo.discount %></td>
        <td><%= link_to 'Show', promo %></td>
        <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
        <td><%= link_to 'Destroy', promo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promo', new_promo_path %>

app/views/promos/new.html.erb
<h1>New Promo</h1>

<%= render 'form' %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @promo.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @promo.content %>
</p>

<p>
  <strong>Product:</strong>
  <%= @promo.product %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @promo.start_date %>
</p>

<p>
  <strong>Finish date:</strong>
  <%= @promo.finish_date %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @promo.discount %>
</p>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>