config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations"}
  root to: "users#index"

  get "/auth/:provider/callback", to: "omni_sessions#create"

  resources :promos

  resources :products
  resources :users do
    collection do
      get 'login', action: :login #users/login
      post 'login', action: :do_login
      delete 'login', action: :logout
      get 'search' # users/search
    end
  end

  
  get 'sells/index'

  get 'sells/:id', to: 'sells#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
	# Validaciones para las columnas que conforman la clase Product
	validates :ref, :price, :quantity, :brand, :name, :description, :size, :color, presence: true
	validates :size, length: {in: 1..3}
	validates :price, numericality: {greater_than: 0}
	validates :ref, uniqueness: true

	# Un producto tiene varios items de linea (Puede interpretarse como que un usuario tiene varios items en una factura)
	has_many :line_items
	has_many :promos
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
  before_action :login_required

  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(products_params)
    if @product.save
      redirect_to products_path, notice: "Todo bien!"
    else
      render "new"
    end  
  end

  private

  def products_params
  	params.require(:product).permit(:ref, :price, :quantity, :brand, :name, :description, :size, :color)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/index.html.erb
<h1>Listando productos</h1>

<table>
	<tr>
		<th>Reference</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Brand</th>
		<th>Name</th>
		<th>Description</th>
		<th>Size</th>
		<th>Color</th>
	</tr>
	<% @products.each do |product|%>
		<tr>
			<td><%= product.ref%></td>
			<td><%= product.price%></td>
			<td><%= product.quantity%></td>
			<td><%= product.brand%></td>
			<td><%= product.name%></td>
			<td><%= product.description%></td>
			<td><%= product.size%></td>
			<td><%= product.color%></td>
			<td><%= link_to 'Ver producto...', product_path(product)%></td>
		</tr>
	<% end %>		
</table>

app/views/products/new.html.erb
<h1>Crear un nuevo Poducto</h1>

<%=form_for @product do |f|%>
	<%= f.label :ref%></br>
	<%= f.text_field :ref%></br>
	<%= f.label :price%>
	<%= f.text_field :price%></br>
	<%= f.label :quantity%>
	<%= f.select :quantity, options_for_select([1,2,3,4,5,6,7,8,9])%></br>
	<%= f.label "Totto"%>
	<%= f.radio_button(:brand, "Totto")%></br>
	<%= f.label "Americanino"%>
	<%= f.radio_button(:brand, "Americanino")%></br>
	<%= f.label "Diesel"%>
	<%= f.radio_button(:brand, "Diesel")%></br>
	<%= f.label :name%>
	<%= f.text_field :name%></br>
	<%= f.label :description%>
	<%= f.text_field :description%></br>
	<%= f.label :size%>
	<%= f.select :size, options_for_select({'TALLA M' => 'M'}) %></br>
	<%= f.label :color%>
	<%= f.select :color,options_for_select(["red", "blue", "gold"])%></br>
	<%= f.submit%>
<%end%>

app/views/products/show.html.erb
<h1>Detalle del producto</h1>

<h4>Ref:</h4><%= @product.ref%> 
<br/>
<h4>Price:</h4> <%=number_to_currency(@product.price)%>
<br/>
<h4>Quantity:</h4> <%= @product.quantity%>
<br/>
<h4>Brand:</h4> <%= @product.brand%>
<br/>
<h4>Name:</h4> <%= @product.name%>
<br/>
<h4>Description:</h4> <%= @product.description%>
<br/>
<h4>Size:</h4> <%= @product.size%>
<br/>
<h4>Color</h4> <%= @product.color%>
<br/>

<%= link_to 'Volver al listado', url_for(controller: :products, action: :index) %>


			
			
			
			
			
			
			
			